# (参考)
# postgresからmysqlに変更
# nginxは自前(embeddedのは使わない)
# https://gitlab.com/gitlab-org/omnibus-gitlab/tree/master/doc/settings
- name: install package for gitlab
  yum: name={{ item }} state=latest
  with_items:
    - curl
    - openssh-server
    - openssh-clients
    - postfix
    - cronie

- name: execute install script (gitlab-ce)
  shell: curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh | bash

- name: execute install script (gitlab-ci)
  shell: curl -sS https://packages.gitlab.com/install/repositories/runner/gitlab-ci-multi-runner/script.rpm.sh | bash

- name: enabled is 0
  replace: dest=/etc/yum.repos.d/{{ item }} regexp="enabled *= *1" replace="enabled=0"
  with_items:
    - gitlab_gitlab-ce.repo
    - runner_gitlab-ci-multi-runner.repo

- name: install gitlab-ce
  yum: name=gitlab-ce enablerepo=gitlab_gitlab-ce

- name: install gitlab-ci
  yum: name=gitlab-ci-multi-runner enablerepo=runner_gitlab-ci-multi-runner,runner_gitlab-ci-multi-runner-source

- name: install gitlab.rb
  template: >
    src={{ item }}.j2
    dest=/etc/gitlab/{{ item }}
    backup=yes
    mode=0600
  with_items:
    - gitlab.rb

- name: replace /opt/gitlab/embedded/service/gitlab-rails/.bundle/config for mysql
  replace: dest=/opt/gitlab/embedded/service/gitlab-rails/.bundle/config regexp='development:test:mysql' replace='development:test'

- name: modify bundle setting for mysql
  shell: source ~/.bash_profile; cd /opt/gitlab/embedded/service/gitlab-rails/; bundle install

- name: reconfigure
  shell: source ~/.bash_profile; gitlab-ctl reconfigure

- name: install virtual host config for gitlab
  template: >
    src={{ item }}.j2
    dest=/etc/nginx/conf.d/{{ item }}
    backup=yes
    mode=0644
  with_items:
    - gitlab-http.conf
  notify: restart nginx
