# mysql 8.0
# インストール後は初期化とユーザー追加は別途必要
- name: install mysql repository
  yum: name={{ item }}
  with_items:
    - https://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm

- name: enabled is 0
  replace: dest=/etc/yum.repos.d/{{ item }} regexp="enabled *= *1" replace="enabled=0"
  with_items:
    - mysql-community-source.repo
    - mysql-community.repo

- name: install mysql8.0
  yum: name=mysql-community-server,mysql-community-devel enablerepo=mysql80-community

- name: add systemctl
  command: systemctl enable mysqld

- name: install my.cnf
  template: >
    src={{ item }}
    dest=/etc/{{ item }}
    backup=yes
    mode=0644
  with_items:
    - my.cnf
  notify: restart mysqld
