- name: check vim.
  stat: path=/usr/local/bin/vim
  register: vim_bin

- block:
  - name: yum install.
    yum: name={{ item }} state=latest
    with_items:
      - lua-devel
      - python-devel
      - ruby-devel
      - ncurses-devel

  - name: clone vim8.
    git: repo=git://github.com/vim/vim.git
         dest=/tmp/vim
         version=v8.1.0037

  - name: make vim8.
    shell: "{{ item }}"
    args:
      chdir: /tmp/vim/src
    with_items:
      - ./configure --with-features=huge --enable-multibyte --enable-luainterp=dynamic --enable-gpm --enable-cscope --enable-fontset --enable-fail-if-missing --prefix=/usr/local --enable-pythoninterp=dynamic --enable-rubyinterp=dynamic
      - make
      - make install
    become: yes

  when: not vim_bin.stat.exists
