- name: check repository
  stat: path=/etc/yum.repos.d/epel.repo
  register: epel_repo

- name: install certbot
  yum:
    name: certbot

- block:
  - name: install certbot
    yum:
      name: certbot
  when: not epel_repo.stat.exists
